const express = require('express');
const path = require('path');
const app = express();

// Set up view engine
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

// Serve static files from the 'public' directory
app.use(express.static(path.join(__dirname, 'public')));

// Quotes data
const quotes = {
    Life: [
        { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
        { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
        { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { text: "Good friends are like stars. You don't always see them, but you know they're always there.", author: "Unknown" },
        { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
        { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
        { text: "Life is a journey that must be traveled no matter how bad the roads and accommodations.", author: "Oliver Goldsmith" },
        { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
        { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
        { text: "We don’t have to be better than anyone else; we just have to be better than we used to be.", author: "Unknown" },
        { text: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
        { text: "The unexamined life is not worth living.", author: "Socrates" },
        { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
        { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
        { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
        { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
        { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
        { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
        { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
        { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
        { text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts" },
        { text: "Life is a journey that must be traveled no matter how bad the roads and accommodations.", author: "Oliver Goldsmith" },
        { text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
        { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
        { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
        { text: "Good friends are like stars. You don't always see them, but you know they're always there.", author: "Unknown" },
        { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
        { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
        { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
        { text: "We don’t have to be better than anyone else; we just have to be better than we used to be.", author: "Unknown" },
        { text: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
        { text: "The unexamined life is not worth living.", author: "Socrates" },
        { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
        { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
        { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
        { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
        { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
        { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
        { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
        { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
        { text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts" },
        { text: "Life is a journey that must be traveled no matter how bad the roads and accommodations.", author: "Oliver Goldsmith" },
        { text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
        { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
        { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
        { text: "Good friends are like stars. You don't always see them, but you know they're always there.", author: "Unknown" },
        { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
        { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
        { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
        { text: "We don’t have to be better than anyone else; we just have to be better than we used to be.", author: "Unknown" },
        { text: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
        { text: "The unexamined life is not worth living.", author: "Socrates" },
        { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
        { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
        
    ],
   Smile: [
    { text: "A smile is the best makeup any girl can wear.", author: "Marilyn Monroe" },
    { text: "Smile, it is the key that fits the lock of everybody's heart.", author: "Anthony J. D'Angelo" },
    { text: "You’re never fully dressed without a smile.", author: "Martin Charnin" },
    { text: "Life is like a mirror. Smile at it and it smiles back at you.", author: "Peace Pilgrim" },
    { text: "Smiling is infectious, you catch it like the flu. When someone smiled at me today, I started smiling too.", author: "Anonymous" },
    { text: "A smile is happiness you’ll find right under your nose.", author: "Tom Wilson" },
    { text: "If you see a friend without a smile; give him one of yours.", author: "Anonymous" },
    { text: "The world always looks brighter from behind a smile.", author: "Anonymous" },
    { text: "A smile can brighten the darkest day.", author: "Anonymous" },
    { text: "Smile, and the world smiles with you.", author: "Anonymous" },
    { text: "Let us always meet each other with a smile, for the smile is the beginning of love.", author: "Mother Teresa" },
    { text: "A smile is the universal welcome.", author: "Max Eastman" },
    { text: "Keep smiling, because life is a beautiful thing and there’s so much to smile about.", author: "Marilyn Monroe" },
    { text: "A warm smile is the universal language of kindness.", author: "William Arthur Ward" },
    { text: "Smile at strangers and you just might change a life.", author: "Steve Maraboli" },
    { text: "A smile is a curve that sets everything straight.", author: "Phyllis Diller" },
    { text: "Your smile will give you a positive countenance that will make people feel comfortable around you.", author: "Les Brown" },
    { text: "Smile! It increases your face value.", author: "Robert Harling" },
    { text: "I have many problems in life, but my lips don’t know that. They always smile.", author: "Charlie Chaplin" },
    { text: "Smile, it’s free therapy.", author: "Douglas Horton" },
    { text: "Because of your smile, you make life more beautiful.", author: "Thich Nhat Hanh" },
    { text: "A smile is the chosen vehicle of all ambiguities.", author: "Herman Melville" },
    { text: "Smile in the mirror. Do that every morning and you’ll start to see a big difference in your life.", author: "Yoko Ono" },
    { text: "Every smile makes you a day younger.", author: "Chinese Proverb" },
    { text: "A smile is the light in your window that tells others that there is a caring, sharing person inside.", author: "Denis Waitley" },
    { text: "A smile is the best way to get away with trouble even if it’s a fake one.", author: "Masashi Kishimoto" },
    { text: "A smile is an inexpensive way to change your looks.", author: "Charles Gordy" },
    { text: "The robbed that smiles, steals something from the thief.", author: "William Shakespeare" },
    { text: "We shall never know all the good that a simple smile can do.", author: "Mother Teresa" },
    { text: "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.", author: "Thich Nhat Hanh" },
    { text: "If you have only one smile in you, give it to the people you love.", author: "Maya Angelou" },
    { text: "One who smiles rather than rages is always the stronger.", author: "Japanese Proverb" },
    { text: "Nothing shakes the smiling heart.", author: "Santosh Kalwar" },
    { text: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh" },
    { text: "A smile is the shortest distance between two people.", author: "Victor Borge" },
    { text: "The real man smiles in trouble, gathers strength from distress, and grows brave by reflection.", author: "Thomas Paine" },
    { text: "Don’t cry because it’s over, smile because it happened.", author: "Dr. Seuss" },
    { text: "Everyone smiles in the same language.", author: "George Carlin" },
    { text: "Always wear a smile sometime during the day, it makes you feel happier and younger.", author: "Kara Goucher" },
    { text: "A smile is the prettiest thing you can wear.", author: "Anonymous" },
    { text: "A smile is a friend maker.", author: "Bangambiki Habyarimana" },
    { text: "You don’t have to be happy to smile.", author: "Daniel Willey" },
    { text: "Smile, it is the key that fits the lock of everybody’s heart.", author: "Anthony J. D’Angelo" },
    { text: "Smile more. Smiling can make you and others happy.", author: "Roy T. Bennett" },
    { text: "A smile is an instant face-lift.", author: "Anonymous" },
    { text: "Your smile is your logo, your personality is your business card, how you leave others feeling after an experience with you becomes your trademark.", author: "Jay Danzie" },
    { text: "Smile at the obstacle, for it is a bridge.", author: "Medusa" },
    { text: "The living should smile, for the dead cannot.", author: "George R.R. Martin" },
    { text: "You’ll find that life is still worthwhile, if you just smile.", author: "Charlie Chaplin" },
    { text: "Smile at the confusion, live for the moments, and know everything happens for a reason.", author: "Albert Schweitzer" },
    { text: "The most beautiful curve on a woman’s body is her smile.", author: "Bob Marley" },
    { text: "Start every day with a smile and get it over with.", author: "W.C. Fields" },
    { text: "A smile is a facelift that’s in everyone’s price range!", author: "Tom Wilson" },
    { text: "If we are not able to smile, then the world will not have peace.", author: "Thich Nhat Hanh" },
    { text: "Smile, even if it’s a sad smile, because sadder than a sad smile is the sadness of not knowing how to smile.", author: "Anonymous" },
    { text: "A smile is the only crooked line that sets things straight.", author: "Phyllis Diller" },
    { text: "The simplest positive action is a smile.", author: "Maxime Lagacé" },
    { text: "Smile. Be open and welcoming.", author: "Ephraim Buchwald" },
    { text: "If you smile when no one else is around, you really mean it.", author: "Andy Rooney" },
    { text: "I wake up every morning with a great smile. I feel so blessed. That’s why I always try to make sure I share my smile with the world.", author: "Anonymous" },
    { text: "A smile is a curve that sets everything straight.", author: "Phyllis Diller" },
    { text: "Keep smiling and the world will smile with you.", author: "Anonymous" },
    { text: "A smile is the best way to get away with trouble even if it’s a fake one.", author: "Masashi Kishimoto" },
    { text: "I add a smile to everything I wear and that has worked great for me.", author: "David White" },
    { text: "Wear a smile and have friends; wear a scowl and have wrinkles.", author: "George Eliot" },
    { text: "If you’re not using your smile, you’re like a man with a million dollars in the bank and no checkbook.", author: "Les Giblin" },
    { text: "Nothing beats a great smile.", author: "Karl Urban" },
    { text: "Smile, it is the key that fits the lock of everybody’s heart.", author: "Anthony J. D’Angelo" },
    { text: "A smile is a curve that sets everything straight.", author: "Phyllis Diller" },
    { text: "Smile in the mirror. Do that every morning and you’ll start to see a big difference in your life.", author: "Yoko Ono" },
    { text: "Smiling makes people feel good and positive, conveying a sense of good-will, rapport and trust.", author: "Anonymous" },
    { text: "A smile is the universal welcome.", author: "Max Eastman" },
    { text: "A smile is a friend maker.", author: "Bangambiki Habyarimana" },
    { text: "Keep smiling, because life is a beautiful thing and there’s so much to smile about.", author: "Marilyn Monroe" },
    { text: "The world always looks brighter from behind a smile.", author: "Anonymous" },
    { text: "A smile is a curve that sets everything straight.", author: "Phyllis Diller" },
    { text: "Every smile makes you a day younger.", author: "Chinese Proverb" },
    { text: "Smile in the mirror. Do that every morning and you’ll start to see a big difference in your life.", author: "Yoko Ono" },
    { text: "A smile is a friend maker.", author: "Bangambiki Habyarimana" },
    { text: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh" },
    { text: "A smile is the prettiest thing you can wear.", author: "Anonymous" },
    { text: "Keep smiling and the world will smile with you.", author: "Anonymous" },
    { text: "A smile is a friend maker.", author: "Bangambiki Habyarimana" },
    { text: "Let us always meet each other with a smile, for the smile is the beginning of love.", author: "Mother Teresa" },
    { text: "A smile is the best way to get away with trouble even if it’s a fake one.", author: "Masashi Kishimoto" },
    { text: "A smile is the only crooked line that sets things straight.", author: "Phyllis Diller" },
    { text: "Smile more. Smiling can make you and others happy.", author: "Roy T. Bennett" },
    { text: "Nothing beats a great smile.", author: "Karl Urban" },
    { text: "Smile at strangers and you just might change a life.", author: "Steve Maraboli" },
    { text: "Always wear a smile sometime during the day, it makes you feel happier and younger.", author: "Kara Goucher" }
],

    Happy: [
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "The only joy in the world is to begin.", author: "Cesare Pavese" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
    { text: "Most people are about as happy as they make up their minds to be.", author: "Abraham Lincoln" },
    { text: "Happiness is a direction, not a place.", author: "Sydney J. Harris" },
    { text: "Happiness is the highest good.", author: "Aristotle" },
    { text: "Happiness is the experience of living every moment with love, grace, and gratitude.", author: "Anonymous" },
    { text: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
    { text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "The secret of happiness is not in doing what one likes, but in liking what one does.", author: "James M. Barrie" },
    { text: "For every minute you are angry, you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
    { text: "Happiness is not a goal; it is a by-product.", author: "Eleanor Roosevelt" },
    { text: "The happiest people don’t have the best of everything, they just make the best of everything.", author: "Anonymous" },
    { text: "Happiness is only real when shared.", author: "Christopher McCandless" },
    { text: "Happiness is the best makeup.", author: "Drew Barrymore" },
    { text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn" },
    { text: "True happiness arises, in the first place, from the enjoyment of oneself.", author: "Joseph Addison" },
    { text: "Happiness is not a state to arrive at, but a manner of traveling.", author: "Margaret Lee Runbeck" },
    { text: "Happiness is a habit—cultivate it.", author: "Elbert Hubbard" },
    { text: "The key to being happy is knowing you have the power to choose what to accept and what to let go.", author: "Dodinsky" },
    { text: "Happiness is an inside job.", author: "William Arthur Ward" },
    { text: "The true secret of happiness lies in taking a genuine interest in all the details of daily life.", author: "William Morris" },
    { text: "Happiness is not found in things you possess, but in what you have the courage to release.", author: "Nathaniel Hawthorne" },
    { text: "The secret to happiness is freedom... And the secret to freedom is courage.", author: "Thucydides" },
    { text: "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.", author: "Anonymous" },
    { text: "The moments of happiness we enjoy take us by surprise. It is not that we seize them, but that they seize us.", author: "Ashley Montagu" },
    { text: "The greatest happiness you can have is knowing that you do not necessarily require happiness.", author: "William Saroyan" },
    { text: "The secret of happiness is to find a congenial monotony.", author: "V.S. Pritchett" },
    { text: "Happiness is not something you experience, it’s something you remember.", author: "Oscar Levant" },
    { text: "Happiness is the settling of the soul into its most appropriate spot.", author: "Aristotle" },
    { text: "Happiness is the secret to all beauty. There is no beauty that is attractive without happiness.", author: "Christian Dior" },
    { text: "The happiest people seem to be those who have no particular cause for being happy except that they are so.", author: "William Ralph Inge" },
    { text: "Happiness is a form of courage.", author: "Holbrook Jackson" },
    { text: "Happiness is the interval between periods of unhappiness.", author: "Don Marquis" },
    { text: "Happiness grows at our own firesides, and is not to be picked in strangers' gardens.", author: "Douglas William Jerrold" },
    { text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle" },
    { text: "Happiness is nothing more than good health and a bad memory.", author: "Albert Schweitzer" },
    { text: "Happiness consists in contentment.", author: "Aristotle" },
    { text: "The true secret of happiness is to enjoy the present, without anxious dependence upon the future.", author: "Lucius Annaeus Seneca" },
    { text: "Happiness is the natural flower of duty.", author: "Phillips Brooks" },
    { text: "Happiness is the secret to all beauty. There is no beauty that is attractive without happiness.", author: "Christian Dior" },
    { text: "The foolish man seeks happiness in the distance; the wise grows it under his feet.", author: "James Oppenheim" },
    { text: "The secret of happiness is to admire without desiring.", author: "Carl Sandburg" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "The talent for being happy is appreciating and liking what you have, instead of what you don’t have.", author: "Woody Allen" },
    { text: "Happiness is not a matter of intensity but of balance, order, rhythm, and harmony.", author: "Thomas Merton" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "Happiness is the best revenge.", author: "Anonymous" },
    { text: "Happiness is a way station between too little and too much.", author: "Channing Pollock" },
    { text: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
    { text: "Happiness is an inside job.", author: "William Arthur Ward" },
    { text: "Happiness is a direction, not a place.", author: "Sydney J. Harris" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "Happiness is a journey, not a destination.", author: "Ben Sweetland" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "Happiness is the best makeup.", author: "Drew Barrymore" },
    { text: "Happiness is a direction, not a place.", author: "Sydney J. Harris" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Happiness is an inside job.", author: "William Arthur Ward" },
    { text: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "Happiness is not a goal; it is a by-product.", author: "Eleanor Roosevelt" },
    { text: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
    { text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt" },
    { text: "Happiness is a journey, not a destination.", author: "Ben Sweetland" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "Happiness is an inside job.", author: "William Arthur Ward" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
    { text: "Happiness is a direction, not a place.", author: "Sydney J. Harris" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
    { text: "Happiness is an inside job.", author: "William Arthur Ward" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "Happiness is a journey, not a destination.", author: "Ben Sweetland" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" }
],

   Sad: [
    { text: "Tears come from the heart and not from the brain.", author: "Leonardo da Vinci" },
    { text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { text: "The best way to cheer yourself is to try to cheer someone else up.", author: "Mark Twain" },
    { text: "Sometimes, you have to cry out all the tears you have to make room for all the happiness that’s coming.", author: "Anonymous" },
    { text: "The darkest hour has only sixty minutes.", author: "Morris Mandel" },
    { text: "It is better to be alone than in bad company.", author: "George Washington" },
    { text: "The sorrow which has no vent in tears may make other organs weep.", author: "Henry Maudsley" },
    { text: "The pain you feel today is the strength you feel tomorrow. For every challenge encountered there is opportunity for growth.", author: "Anonymous" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "The only time you should ever look back is to see how far you've come.", author: "Anonymous" },
    { text: "It's okay to cry when there’s too much on your mind. The clouds rain too when things get heavy.", author: "Anonymous" },
    { text: "You cannot protect yourself from sadness without protecting yourself from happiness.", author: "Jonathan Safran Foer" },
    { text: "Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.", author: "Henry Wadsworth Longfellow" },
    { text: "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.", author: "Christopher Morley" },
    { text: "To have felt too much is to end in feeling nothing.", author: "Dorothy Thompson" },
    { text: "The good times of today are the sad thoughts of tomorrow.", author: "Bob Marley" },
    { text: "We must understand that sadness is an ocean, and sometimes we drown, while other days we are forced to swim.", author: "R.M. Drake" },
    { text: "Our sweetest songs are those that tell of saddest thought.", author: "Percy Bysshe Shelley" },
    { text: "Sadness is but a wall between two gardens.", author: "Khalil Gibran" },
    { text: "There is no worse sorrow than remembering happiness in the day of sorrow.", author: "Alfred de Musset" },
    { text: "Sadness is almost never anything but a form of fatigue.", author: "Andre Gide" },
    { text: "It’s easy to cry when you realize that everyone you love will reject you or die.", author: "Chuck Palahniuk" },
    { text: "Tears are the summer showers to the soul.", author: "Alfred Austin" },
    { text: "It’s sad when someone you know becomes someone you knew.", author: "Henry Rollins" },
    { text: "The walls we build around us to keep sadness out also keeps out the joy.", author: "Jim Rohn" },
    { text: "You meet everyone twice in this life, when they come and when they go.", author: "C.C. Aurel" },
    { text: "It is sad not to love, but it is much sadder not to be able to love.", author: "Miguel de Unamuno" },
    { text: "Some days are just bad days, that's all. You have to experience sadness to know happiness, and I remind myself that not every day is going to be a good day, that's just the way it is!", author: "Dita Von Teese" },
    { text: "The word 'happy' would lose its meaning if it were not balanced by sadness.", author: "Carl Jung" },
    { text: "When you are happy, you enjoy the music. But, when you are sad, you understand the lyrics.", author: "Frank Ocean" },
    { text: "Behind every sweet smile, there is a bitter sadness that no one can ever see and feel.", author: "Tupac Shakur" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "The soul would have no rainbow had the eyes no tears.", author: "John Vance Cheney" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "You cannot protect yourself from sadness without protecting yourself from happiness.", author: "Jonathan Safran Foer" },
    { text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { text: "Sadness is but a wall between two gardens.", author: "Khalil Gibran" },
    { text: "There is no worse sorrow than remembering happiness in the day of sorrow.", author: "Alfred de Musset" },
    { text: "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.", author: "Christopher Morley" },
    { text: "To have felt too much is to end in feeling nothing.", author: "Dorothy Thompson" },
    { text: "The good times of today are the sad thoughts of tomorrow.", author: "Bob Marley" },
    { text: "You cannot protect yourself from sadness without protecting yourself from happiness.", author: "Jonathan Safran Foer" },
    { text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { text: "Sadness is but a wall between two gardens.", author: "Khalil Gibran" },
    { text: "The soul would have no rainbow had the eyes no tears.", author: "John Vance Cheney" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "It’s sad when someone you know becomes someone you knew.", author: "Henry Rollins" },
    { text: "The word 'happy' would lose its meaning if it were not balanced by sadness.", author: "Carl Jung" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "You cannot protect yourself from sadness without protecting yourself from happiness.", author: "Jonathan Safran Foer" },
    { text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { text: "Sadness is but a wall between two gardens.", author: "Khalil Gibran" },
    { text: "The soul would have no rainbow had the eyes no tears.", author: "John Vance Cheney" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "It’s sad when someone you know becomes someone you knew.", author: "Henry Rollins" },
    { text: "The word 'happy' would lose its meaning if it were not balanced by sadness.", author: "Carl Jung" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "You cannot protect yourself from sadness without protecting yourself from happiness.", author: "Jonathan Safran Foer" },
    { text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { text: "Sadness is but a wall between two gardens.", author: "Khalil Gibran" },
    { text: "The soul would have no rainbow had the eyes no tears.", author: "John Vance Cheney" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "It’s sad when someone you know becomes someone you knew.", author: "Henry Rollins" },
    { text: "The word 'happy' would lose its meaning if it were not balanced by sadness.", author: "Carl Jung" },
    { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
    { text: "Tears are the silent language of grief.", author: "Voltaire" },
    { text: "You cannot protect yourself from sadness without protecting yourself from happiness.", author: "Jonathan Safran Foer" },
    { text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { text: "Sadness is but a wall between two gardens.", author: "Khalil Gibran" }
    
    ],
    Travel: [
    { text: "The world is a book, and those who do not travel read only one page.", author: "Saint Augustine" },
    { text: "Travel makes one modest. You see what a tiny place you occupy in the world.", author: "Gustave Flaubert" },
    { text: "Travel is the only thing you buy that makes you richer.", author: "Anonymous" },
    { text: "The journey not the arrival matters.", author: "T.S. Eliot" },
    { text: "To travel is to live.", author: "Hans Christian Andersen" },
    { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
    { text: "Travel far, travel wide, travel often.", author: "Anonymous" },
    { text: "Take only memories, leave only footprints.", author: "Chief Seattle" },
    { text: "Life is short and the world is wide.", author: "Simon Raven" },
    { text: "We travel not to escape life, but for life not to escape us.", author: "Anonymous" },
    { text: "The best education I have ever received was through travel.", author: "Anonymous" },
    { text: "Travel brings power and love back into your life.", author: "Rumi" },
    { text: "Travel is the only thing you can buy that makes you richer.", author: "Anonymous" },
    { text: "Adventure is worthwhile.", author: "Aesop" },
    { text: "Travel and change of place impart new vigor to the mind.", author: "Seneca" },
    { text: "Oh the places you’ll go.", author: "Dr. Seuss" },
    { text: "To travel is to discover that everyone is wrong about other countries.", author: "Aldous Huxley" },
    { text: "The more I traveled, the more I realized that fear makes strangers of people who should be friends.", author: "Shirley MacLaine" },
    { text: "Traveling – it leaves you speechless, then turns you into a storyteller.", author: "Ibn Battuta" },
    { text: "Travel far enough, you meet yourself.", author: "David Mitchell" },
    { text: "Take only pictures, leave only footprints.", author: "Anonymous" },
    { text: "Travel is the ultimate inspiration.", author: "Anonymous" },
    { text: "Travel is not about the places you go, but the people you meet.", author: "Anonymous" },
    { text: "To travel is to take a journey into yourself.", author: "Danny Kaye" },
    { text: "Wander often, wonder always.", author: "Anonymous" },
    { text: "Travel is the only thing you can spend money on that makes you richer.", author: "Anonymous" },
    { text: "The best views come after the hardest climbs.", author: "Anonymous" },
    { text: "Travel is never a matter of money but of courage.", author: "Paulo Coelho" },
    { text: "We travel not to escape life, but for life not to escape us.", author: "Anonymous" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "Travel expands the mind and fills the gap.", author: "Sheda Savage" },
    { text: "The world is full of beautiful places. Let your heart be one of them.", author: "Anonymous" },
    { text: "Travel is a way of self-discovery.", author: "Anonymous" },
    { text: "Travel doesn’t become adventure until you leave yourself behind.", author: "Anonymous" },
    { text: "Traveling allows you to become so many different versions of yourself.", author: "Anonymous" },
    { text: "Travel brings power and love back into your life.", author: "Rumi" },
    { text: "Travel makes one modest. You see what a tiny place you occupy in the world.", author: "Gustave Flaubert" },
    { text: "Travel is the only thing you can buy that makes you richer.", author: "Anonymous" },
    { text: "Travel far enough, you meet yourself.", author: "David Mitchell" },
    { text: "Take only pictures, leave only footprints.", author: "Anonymous" },
    { text: "Travel is the ultimate inspiration.", author: "Anonymous" },
    { text: "Travel is not about the places you go, but the people you meet.", author: "Anonymous" },
    { text: "To travel is to take a journey into yourself.", author: "Danny Kaye" },
    { text: "Wander often, wonder always.", author: "Anonymous" },
    { text: "Travel is the only thing you can spend money on that makes you richer.", author: "Anonymous" },
    { text: "The best views come after the hardest climbs.", author: "Anonymous" },
    { text: "Travel is never a matter of money but of courage.", author: "Paulo Coelho" },
    { text: "We travel not to escape life, but for life not to escape us.", author: "Anonymous" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "Travel expands the mind and fills the gap.", author: "Sheda Savage" },
    { text: "The world is full of beautiful places. Let your heart be one of them.", author: "Anonymous" },
    { text: "Travel is a way of self-discovery.", author: "Anonymous" },
    { text: "Travel doesn’t become adventure until you leave yourself behind.", author: "Anonymous" },
    { text: "Traveling allows you to become so many different versions of yourself.", author: "Anonymous" }
],

Inspire: [
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
    { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
    { text: "The harder the conflict, the greater the triumph.", author: "George Washington" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
    { text: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { text: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
    { text: "People who are crazy enough to think they can change the world are the ones who do.", author: "Rob Siltanen" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "The real test is not whether you avoid this failure, because you won’t. It’s whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere.", author: "Barack Obama" },
    { text: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "Don’t let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
    { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
    { text: "Get busy living or get busy dying.", author: "Stephen King" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.", author: "James Cameron" },
    { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it.", author: "Jordan Belfort" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
]

};

// Routes
app.get('/', (req, res) => {
    res.render('index', { quotes: quotes.Life });
});

app.get('/category/:category', (req, res) => {
    const category = req.params.category;
    if (quotes[category]) {
        res.render('category', { category: category, quotes: quotes[category] });
    } else {
        res.redirect('/');
    }
});

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log('Server running on port ${PORT}');
});
